### ISSUE TITLE
How to run the demo

### ISSUE THREAD

**Issue by luotianhang** [siriusdemon/Build-Your-Own-Face-Model#22]
this is really a good work ,but i find the demo is not working, i use the imgs in this project

**Comment by siriusdemon** [comment]
More detail ?

**Comment by ChengSongyang** [comment]
我也发现不能运行，用project自带的abc图片会报如下的错：
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/人脸检测及关键点检测/Build-Your-Own-Face-Model-master/package/detection/demo.py", line 26, in <module>
    res = centerface.detect(img)
  File "C:\Users\Administrator\Desktop\人脸检测及关键点检测\Build-Your-Own-Face-Model-master\package\detection\centerface\api.py", line 98, in detect_pipeline
    box_land_list = decode_many(preds)
  File "C:\Users\Administrator\Desktop\人脸检测及关键点检测\Build-Your-Own-Face-Model-master\package\detection\centerface\api.py", line 53, in decode_many
    xs, ys = np.nonzero(hm_)
ValueError: not enough values to unpack (expected 2, got 1)


猜测根本没有检测到人脸，所以np.nonzero中的hm_值全为0

**Comment by ChengSongyang** [comment]
> More detail ?

我也发现不能运行，用project自带的abc图片会报如下的错：
Traceback (most recent call last):
File "C:/Users/Administrator/Desktop/人脸检测及关键点检测/Build-Your-Own-Face-Model-master/package/detection/demo.py", line 26, in 
res = centerface.detect(img)
File "C:\Users\Administrator\Desktop\人脸检测及关键点检测\Build-Your-Own-Face-Model-master\package\detection\centerface\api.py", line 98, in detect_pipeline
box_land_list = decode_many(preds)
File "C:\Users\Administrator\Desktop\人脸检测及关键点检测\Build-Your-Own-Face-Model-master\package\detection\centerface\api.py", line 53, in decode_many
xs, ys = np.nonzero(hm_)
ValueError: not enough values to unpack (expected 2, got 1)

猜测根本没有检测到人脸，所以np.nonzero中的hm_值全为0
